version: '1.0'

services:
    postgres:
        container_name: postgres14_container
        image: postgres:14.10-alpine3.19
        environment:
            POSTGRES_USER: ${POSTGRES_USER:-postgres}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
            PGDATA: /data/postgres
        ports:
            - 5432:5432
        expose:
            - 5432
        restart: unless-stopped

    pgadmin:
        container_name: pgadmin4_container
        image: dpage/pgadmin4
        environment:
            PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
            PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-changeme}
            PGADMIN_CONFIG_SERVER_MODE: 'False'

        ports:
            - "${PGADMIN_PORT:-5050}:80"
        restart: unless-stopped
networks:
  app_network:
    driver: bridge
